homeassistant:
  name: Schedule Dev
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  auth_providers:
    - type: homeassistant
      username: admin
      password: admin

config:
api:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_text: !include input_text.yaml

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/dayschedule-editor-card.js
#   development_repo: /workspaces/ha-core

